### ISSUE TITLE
pysbol2-assigned role URIs fail with lookup error

### ISSUE THREAD

**Issue by eyesmo** [SynBioDex/tyto#10]
When I assign an SO term to a role in pysbol2 like so:
```
spacer3.roles = sb.SO + '0002223'
AF_SpisPink_Cassette.roles = [sb.SO + '0000352', sb.SO + '0000546'] #SO terms for 'DNA' and 'engineered sequence'

print(spacer3.roles)
>> ['http://identifiers.org/so/SO:0002223']

print(AF_SpisPink_Cassette.roles[1])
>> http://identifiers.org/so/SO:0000546  #Hyperlink to SO term for designed_sequence
```
and then try to retrieve the SO term with TYTO, I get a lookup error to an http URI:
```
SO.get_term_by_uri(AF_SpisPink_Cassette.roles[1])
>>'\n                <http'
>> LookupError: http://identifiers.org/so/SO:0000546 not found
```
However, if I instead manually enter the URI and start with https instead of http, and remove '/so/' I get no error:
```
SO.get_term_by_uri('https://identifiers.org/SO:0000546')
>> '\n                <http'
>> designed_sequence
```
Is there a way to make sure SBOL assigns the working URI, or to tweak TYTO to accept the URI that SBOL is auto-generating for me? Also, what's the best way to store the output term while getting rid of the `'\n                <http'` component?

**Comment by bbartley** [comment]
Apparently the built-in constants in pySBOL follow the alternate URI format that differs slightly from the format preferred by tyto.  The quick workaround is to use the symbols defined by tyto rather than the ones built into pySBOL, eg:
```
spacer3.roles = SO.inert_dna_spacer
AF_SpisPink_Cassette.roles = SO.engineered_sequence
```
As for your last question, I'm not sure yet what is going on there.  It looks like it is flushing a buffer somewhere after catching an exception.  I haven't identified the exact cause yet though.

**Comment by eyesmo** [comment]
Tried
```
spacer3.roles = SO.inert_dna_spacer
```
and the output was
```
unexpected '{' in field name
unexpected '{' in field name
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-52-4e2009041415> in <module>()
----> 1 spacer3.roles = SO.inert_dna_spacer
      2 SO.get_term_by_uri(spacer3.roles)

/usr/local/lib/python3.6/dist-packages/tyto/owlet.py in __getattr__(self, name)
    169             return self.__getattribute__(name)
    170         else:
--> 171             return self.__getattribute__('get_uri_by_term')(name)
    172 
    173 

/usr/local/lib/python3.6/dist-packages/tyto/owlet.py in get_uri_by_term(self, term)
    140             '''.format(sanitized_term=term.replace('_', ' '))
    141         error_msg = '{} not a valid ontology term'.format(term)
--> 142         response = self._query(query, error_msg)[0]
    143         return self._to_user(response)
    144 

/usr/local/lib/python3.6/dist-packages/tyto/owlet.py in _query(self, sparql, error_msg)
     75 
     76         if not len(response):
---> 77             raise LookupError(error_msg)
     78         return response
     79 

LookupError: inert_dna_spacer not a valid ontology term
```
got basically the same output for `SO.engineered_sequence` as well.


If it helps as context, here's the packages I'm working with in this Colab notebook:
```
!pip install sbol2
!pip install tyto
import sbol2 as sb
from sbol2 import *
from tyto import SO, SBO
```

**Comment by jakebeal** [comment]
Looks like the old forms are there in pySBOL2, because that's what the SBOL 2.x spec used. Thus TYTO should support both forms, and likely have a user preference that defaults to the compact identifiers.org form but allows the old form as well for compatibility with pySBOL2.

**Comment by bbartley** [comment]
In addition to needing support for the alternative identifiers.org namespace, @eyesmo has also uncovered 2 bugs here compounding on each other.  I'll get a patch out tomorrow.

**Comment by jakebeal** [comment]
Did this patch make it out yet?

**Comment by eyesmo** [comment]
@jakebeal @bbartley tried again, here's the input and output:
```
uri = spacer3.roles[0]
SO.get_term_by_uri(uri)

> '\n                <http'
> '\n                <http'
> ---------------------------------------------------------------------------
> LookupError                               Traceback (most recent call last)
> <ipython-input-21-14decc639e16> in <module>()
>       1 uri = spacer3.roles[0]
> ----> 2 SO.get_term_by_uri(uri)
> 
> 1 frames
> /usr/local/lib/python3.6/dist-packages/tyto/owlet.py in _query(self, sparql, error_msg)
>      75 
>      76         if not len(response):
> ---> 77             raise LookupError(error_msg)
>      78         return response
>      79 
> 
> LookupError: http://identifiers.org/so/SO:0002223 not found
```

**Comment by bbartley** [comment]
@eyesmo apologies for the delay.  These fixes have been deployed in a new package.  You will need to upgrade, something like:
```
pip3 install tyto --upgrade
...
Successfully installed tyto-1.0a2
```

**Comment by eyesmo** [comment]
Excellent, thanks! It's working well now.
