### ISSUE TITLE
Support large ontologies without a SPARQL endpoint

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#12]
There are a number of large ontologies without a live SPARQL endpoint, such as NCIT, CHEBI, and PubChem.
It would be great if tyto can support these and, more generally, provide a framework for setting up new RESTFUL API interactions

**Comment by bbartley** [comment]
#24 implemented a general framework for supporting REST APIs

Note NCIT is supported by the SPARQL endpoint at Ontobee.  Support for PubChem is requested in #20 

A new issue for CHEBI has been filed at #28

Marking this as resolved
