### ISSUE TITLE
"unexpected '{' in field name"

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#15]
After a lookup fails in tyto, I start getting a curious warning message telling me: "unexpected '{' in field name" every time that I do another lookup

Minimal reproducing example: 
```
import tyto

tyto.SO.get_uri_by_term('CDS')
try:
    tyto.SO.get_uri_by_term('sdfsdfsds')
except LookupError:
    'expected error'
tyto.SO.get_uri_by_term('CDS')
```

The first CDS lookup is normal.
The second returns the expected value, but also prints `unexpected '{' in field name`

**Comment by bbartley** [comment]
This is one of the issues described in #10 which have now been resolved.  Upgrading to a2 should fix the problem
```
pip3 install tyto --upgrade
...
Successfully installed tyto-1.0a2

**Comment by jakebeal** [comment]
Thanks; I'd fallen behind without realizing it.
