### ISSUE TITLE
Failure to look up some SO terms

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#16]
Some SO term lookups are failing.
The ones that it has happened to me for so far all have underscores in their names.

```
tyto.SO.get_uri_by_term('5_prime_UTR_variant')
tyto.SO.get_uri_by_term('promoter_element')
tyto.SO.get_uri_by_term('ribosome_entry_site')
```

**Comment by bbartley** [comment]
This is one of the issues described in #10 which have now been resolved. Upgrading to a2 should fix the problem

pip3 install tyto --upgrade
...
Successfully installed tyto-1.0a2

**Comment by jakebeal** [comment]
Thanks; upgrading resolved this issue.
