### ISSUE TITLE
Style of methods vs constants

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/tyto#2]
Currently both ontology terms and methods are written in snake case.
```
SBO.systems_biology_representation
```
vs
```
SBO.get_term_by_uri('...')
```
Given the large number of symbols associated with an ontology, it might be useful to have a stylistic convention to distinguish ontology terms from methods.  For example, by using camel case for methods, e.g.,
```
SBO.getTermByURI(...)
```
Although this would put us in opposition of Python style standards.

Another option would be to make all methods static.

**Comment by jakebeal** [comment]
Decision: snake case is fine; not an issue after all.
