### ISSUE TITLE
Adding support for tax_id's

### ISSUE THREAD

**Issue by PRUBHTEJ** [SynBioDex/tyto#23]
Is there a way, through which we can add support for the **tax_id** as well, apart from the already existing ontologies?
(https://www.ncbi.nlm.nih.gov/taxonomy)

**Comment by bbartley** [comment]
Yes, this should be fairly straightforward to implement.  You can define your own interfaces for ontologies.  If you don't want to wait for me to implement it, follow the pattern in https://github.com/SynBioDex/tyto/blob/master/tyto/so.py
