### ISSUE TITLE
What is the variable for "degree Celsius"?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#29]
I can't figure out what the variable is supposed to be for a two-part term like "degree Celsius"

```
>>> tyto.OM.get_uri_by_term('degree Celsius')
'http://www.ontology-of-units-of-measure.org/resource/om-2/degreeCelsius'

>>> tyto.OM.degreeCelsius
LookupError: degreeCelsius not a valid ontology term

>>> tyto.OM.degree_Celsius
LookupError: degree_Celsius not a valid ontology term

>>> tyto.OM.degree_celsius
LookupError: degree_celsius not a valid ontology term
```

Is there a variable for this, or is this something I have to use `get_uri_by_term` to find?

**Comment by bbartley** [comment]
`tyto.OM.get_uri_by_term('Celsius temperature')` is the immediate solution

Most of the other ontologies are implemented in a way that allows for replacing spaces in terms with underscores.  For whatever reason, this hasn't been implemented in OM yet though.

**Comment by jakebeal** [comment]
Got it, thank you.

One clarification: is there some reason that I should be using 'Celsius temperature' rather than 'degree Celsius' for the unit?  I believe 'degree Celsius' is what I want in order to say something like '37 C'

**Comment by bbartley** [comment]
I think you are right, `Celsius temperature` more appropriately refers to a type of measurement -- if you are just looking for a unit, as OM is used in SBOL, then `degree Celsisus` is an actual instance of an OM `unit`

**Comment by bbartley** [comment]
`OM.degree_Celsius` is supported in #31
