### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#36]
This needs to have documentation that makes sufficient sense for novice users

**Comment by PRUBHTEJ** [comment]
I'd love to help!

**Comment by bbartley** [comment]
@PRUBHTEJ currently tyto is configured to build auto-documentation using the readthedocs service.  Since these docs are currently barebones, feel free to expand on them and submit any updates through a PR.  The configuration and documentation files are in the `docs` directory.

**Comment by PRUBHTEJ** [comment]
Right, I shall do that!
