### ISSUE TITLE
Tyto seems to stick

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/tyto#51]
If I do a bunch of calls to tyto it seems to get stuck. Where it sticks seems to depend on on how long ago the previous call was. Is there some kind of limit on the number of calls allowed?

**Comment by bbartley** [comment]
@JMante1   You are right, there is likely a rate limit set by the ontology look-up services.  I plan to inquire with the maintainers, but until then, tyto doesn't restrict the rate of queries.

Which query method is sticking?  I implemented local caching on some of the query methods to avoid overwhelming the services with too many requests.  However, not all of the methods implement caching currently.

Related issue here: https://github.com/SynBioDex/tyto/issues/18

**Comment by JMante1** [comment]
Thanks for the clarification. Is the caching per run of a programme, storing previous queries, or storing a local owl file?

The queries that are sticking are either SO or NCBITaxon lookup (I am using both and the code tends to stop at either on or the other). It seems like it is promoter and Komagataella pastoris that cause issues but this can also just be because they are the two most used terms in the data set.

**Comment by bbartley** [comment]
Is it just hanging, or are you seeing anything like an HTTP503 reported by tyto in standard out (it won't throw an exception, but it should log an HTTP error to standard out if it encounters one)?

**Comment by JMante1** [comment]
It just hangs. I haven't seen an http503 but that could be due to the wrapping of the function in a print statement?

**Comment by bbartley** [comment]
OK, I sent a message to the Ontobee maintainers to inquire about the rate-limit.  In the meantime, the best advice I can offer is to maybe empirically test rate-limited queries (maybe sleep for 10ms between requests?).

**Comment by udp** [comment]
There’s definitely no rate limit on OLS, fwiw

**Comment by jakebeal** [comment]
I am closing this as apparently either resolved or obsolete; @JMante1, if this is still an issue, please reopen.
