### ISSUE TITLE
OWL node-ids contaminating SO query results

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#65]
This error was observed using tyto 1.2 on a Mac.

When evaluating `tyto.SO.deletion` there is an ambiguous term exception raised, because searching for deletion finds two different items: `http://purl.obolibrary.org/obo/SO_0000159` (as expected) and `nodeID://b426842858`, which is an owl Axiom:
```
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/SO_0000159"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">loinc:LA6692-3</owl:annotatedTarget>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Deletion</rdfs:label>
    </owl:Axiom>
```

There are two different things coming together to create this problem:
1. The query is being done case-insensitive, which is a deliberate design choice
2. SO has decided to include case-sensitive information in the ontology, which is not typical.

**Comment by jakebeal** [comment]
Two possible ways to solve this problem:
- Make queries case-sensitive. This would not work in general, but might be good for some specific cases.
- Filter out anonymous node values (`nodeID://` URIs, which are not a recognized URI schema)

I think the second might be a good approach.

**Comment by bbartley** [comment]
What about this?  First, attempt an exact, case-sensitive match first (leaving out the FILTER clause here: https://github.com/SynBioDex/tyto/blob/master/tyto/endpoint/endpoint.py#L77), followed by a case-insensitive match if the first one fails (including the FILTER clause)?

**Comment by jakebeal** [comment]
Yes, I think that would work.
