### ISSUE TITLE
tyto 1.2.2 and tyto 1.3 cause sbol-utilities tests to be slow and fail

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#71]
When using tyto 1.2.2 and 1.3, the `test_calculate_sequences` set of tests in SBOL utilities become very slow (seconds to minutes) and fail.

The failure appears to be due to a change in how `tyto.SO.get_term_by_uri` works, as this no longer returns a string, but instead returns a `tyto.tyto.Term`, which is a breaking change.

Here is some code that shows the problem, which is raising exceptions when I try to regularize the form of a term:
```
>>> tyto.SO.get_uri_by_term(tyto.SO.get_term_by_uri('https://identifiers.org/SO:0000755'))
LookupError: plasmid_vector is not a valid ontology term
>>> foo = tyto.SO.get_term_by_uri('https://identifiers.org/SO:0000755')
>>> foo
plasmid_vector
>>> tyto.SO.get_uri_by_term(foo)
LookupError: plasmid_vector is not a valid ontology term
>>> tyto.SO.get_uri_by_term('plasmid_vector')
'https://identifiers.org/SO:0000755'
>>> foo == 'plasmid_vector'
False
>>> foo[0:]
'https://identifiers.org/SO:0000755'
```

**Comment by bbartley** [comment]
Fixed by #72
