### ISSUE TITLE
Enable more aggressive caching

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#9]
For tractably sized ontologies (e.g., not NCIT), it would be good to enable much faster interaction and offline operation by aggressively caching ontologies.

Note: this interacts with #1

**Comment by bjkeller** [comment]
Usually, caching means only keeping requested items locally. For large ontologies, it would make sense to only cache frequently requested terms.

**Comment by jakebeal** [comment]
Yes --- this is essentially a "memory page size" question.  

I suspect a good heuristic would be to set a threshold of N terms (defaulting to some reasonable number list 1000), and figure out an appropriate SPARQL query that can spider out through relations in the ontology until you either get a fragment that's larger than N or until you get the full ontology.

**Comment by bbartley** [comment]
#24 implements caching using Python's `functools` with a default size of 1000 (but is user-configurable)
